server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /finax

spring: 
  freemarker:
    suffix: .html
    request-context-attribute: request
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finax?useSSL=false&characterEncoding=utf8
    username: root
    password: Passw0rd

mybatis-plus:
  mapper-locations: classpath:/mappings/**/*.xml
  typeAliasesPackage: com.xichoo.finax.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
  configuration:
    # 是否开启驼峰命名规则映射
    map-underscore-to-camel-case: true
    # 是否映射查询结果中包含空值的列
    call-setters-on-nulls: true
    # 打印执行sql
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl